import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import "./styles.css";

const seed=[
{id:1,name:"Oversized Essential Tee",category:"Men",price:49,colors:["Black","Cream","White"],sizes:["S","M","L","XL"],stock:42,badge:"NEW",image:"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85"},
{id:2,name:"Signature Blazer",category:"Women",price:129,colors:["Charcoal","Cream"],sizes:["XS","S","M","L","XL"],stock:18,badge:"BESTSELLER",image:"https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=900&q=85"},
{id:3,name:"Essential Hoodie",category:"Men",price:79,colors:["Taupe","Cream","Black"],sizes:["S","M","L","XL","XXL"],stock:27,badge:"LIMITED",image:"https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=85"},
{id:4,name:"Linen Relaxed Shirt",category:"Women",price:69,colors:["Natural","Beige","Black"],sizes:["XS","S","M","L","XL"],stock:31,badge:"",image:"https://images.unsplash.com/photo-1605763240000-7e93b172d754?auto=format&fit=crop&w=900&q=85"}
];

function App(){
 const [products,setProducts]=useState(()=>JSON.parse(localStorage.getItem("ssp_products")||"null")||seed);
 const [cart,setCart]=useState(()=>JSON.parse(localStorage.getItem("ssp_cart")||"[]"));
 const [wish,setWish]=useState(()=>JSON.parse(localStorage.getItem("ssp_wish")||"[]"));
 const [view,setView]=useState("home"),[selected,setSelected]=useState(null),[category,setCategory]=useState("All");
 const [admin,setAdmin]=useState(false),[search,setSearch]=useState(""),[notice,setNotice]=useState("");
 useEffect(()=>localStorage.setItem("ssp_products",JSON.stringify(products)),[products]);
 useEffect(()=>localStorage.setItem("ssp_cart",JSON.stringify(cart)),[cart]);
 useEffect(()=>localStorage.setItem("ssp_wish",JSON.stringify(wish)),[wish]);
 const filtered=useMemo(()=>products.filter(p=>(category==="All"||p.category===category)&&p.name.toLowerCase().includes(search.toLowerCase())),[products,category,search]);
 const total=cart.reduce((s,i)=>s+i.price*i.qty,0);
 const toast=m=>{setNotice(m);setTimeout(()=>setNotice(""),2200)};
 const add=(p,size=p.sizes[Math.min(1,p.sizes.length-1)],color=p.colors[0])=>{setCart(c=>{const old=c.find(i=>i.id===p.id&&i.size===size&&i.color===color);return old?c.map(i=>i===old?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1,size,color}]});toast("Added to bag")};
 const remove=id=>setCart(c=>c.filter(i=>i.id!==id));
 const updateQty=(id,delta)=>setCart(c=>c.map(i=>i.id===id?{...i,qty:Math.max(1,i.qty+delta)}:i));
 const saveProduct=p=>setProducts(ps=>ps.some(x=>x.id===p.id)?ps.map(x=>x.id===p.id?p:x):[...ps,{...p,id:Date.now()}]);
 const deleteProduct=id=>setProducts(ps=>ps.filter(p=>p.id!==id));
 return <div>
  <div className="announcement">FREE INTERNATIONAL SHIPPING ON ORDERS OVER $150</div>
  <header><button className="hamb" onClick={()=>setView("shop")}>☰</button><button className="logo" onClick={()=>setView("home")}><b>SS</b> PASSION</button>
   <nav><button onClick={()=>{setCategory("Men");setView("shop")}}>MEN</button><button onClick={()=>{setCategory("Women");setView("shop")}}>WOMEN</button><button onClick={()=>{setCategory("All");setView("shop")}}>NEW ARRIVALS</button><button onClick={()=>setView("collections")}>COLLECTIONS</button><button onClick={()=>setView("journal")}>JOURNAL</button></nav>
   <div className="actions"><input value={search} onChange={e=>{setSearch(e.target.value);setView("shop")}} placeholder="Search"/><button onClick={()=>setView("cart")}>Bag ({cart.reduce((s,i)=>s+i.qty,0)})</button><button onClick={()=>setAdmin(!admin)}>Admin</button></div>
  </header>
  {notice&&<div className="toast">{notice}</div>}
  {admin?<Admin products={products} save={saveProduct} remove={deleteProduct} close={()=>setAdmin(false)}/>:view==="home"?<Home go={setView} products={products} add={add} wish={wish} setWish={setWish}/>:view==="shop"?<Shop products={filtered} category={category} setCategory={setCategory} open={setSelected} add={add} wish={wish} setWish={setWish}/>:view==="cart"?<Cart cart={cart} total={total} updateQty={updateQty} remove={remove} checkout={()=>setView("checkout")}/>:view==="checkout"?<Checkout total={total} cart={cart}/>:<Editorial type={view}/>}
  {selected&&<Product p={selected} close={()=>setSelected(null)} add={add} wish={wish} setWish={setWish}/>}
  <footer><div><b>SS PASSION</b><p>Wear your passion.<br/>Timeless pieces. Modern attitude.</p></div><div><h4>SHOP</h4><p>Men<br/>Women<br/>New Arrivals<br/>Collections<br/>Sale</p></div><div><h4>HELP</h4><p>Shipping<br/>Returns<br/>Size Guide<br/>Track Order<br/>Contact</p></div><div><h4>JOIN SS PASSION</h4><p>New drops, exclusive releases and stories.</p><input placeholder="Your email address"/></div></footer>
 </div>
}

function Home({go,products,add,wish,setWish}){return <><section className="hero"><div><small>SS PASSION</small><h1>WEAR YOUR<br/>PASSION.</h1><p>Timeless pieces. Modern attitude.</p><button onClick={()=>go("shop")}>SHOP COLLECTION</button></div></section><section className="section"><small>FRESH DROPS</small><h2>NEW ARRIVALS</h2><Grid products={products} add={add} wish={wish} setWish={setWish}/></section><section className="categories"><button onClick={()=>go("shop")}>MEN</button><button onClick={()=>go("shop")}>WOMEN</button><button onClick={()=>go("shop")}>ESSENTIALS</button></section><section className="manifesto"><small>THE SS PASSION PHILOSOPHY</small><h2>Style should feel <i>like you.</i></h2><p>Considered everyday pieces for people who want modern fashion without losing their individuality.</p></section></>}

function Grid({products,add,wish,setWish}){return <div className="grid">{products.map(p=><article key={p.id} className="card"><button className="heart" onClick={()=>setWish(w=>w.includes(p.id)?w.filter(x=>x!==p.id):[...w,p.id])}>{wish.includes(p.id)?"♥":"♡"}</button>{p.badge&&<span className="badge">{p.badge}</span>}<img src={p.image}/><h3>{p.name}</h3><p>${p.price.toFixed(2)}</p><button className="quick" onClick={()=>add(p)}>QUICK ADD</button></article>)}</div>}

function Shop({products,category,setCategory,open,add,wish,setWish}){return <section className="section shop"><div className="shoptop"><div><small>SS PASSION / SHOP</small><h1>{category==="All"?"ALL PRODUCTS":category.toUpperCase()}</h1></div><div className="filters">{["All","Men","Women"].map(x=><button className={category===x?"active":""} onClick={()=>setCategory(x)}>{x}</button>)}</div></div><div className="grid">{products.map(p=><article key={p.id} className="card" onClick={()=>open(p)}><button className="heart" onClick={e=>{e.stopPropagation();setWish(w=>w.includes(p.id)?w.filter(x=>x!==p.id):[...w,p.id])}}>{wish.includes(p.id)?"♥":"♡"}</button>{p.badge&&<span className="badge">{p.badge}</span>}<img src={p.image}/><h3>{p.name}</h3><p>${p.price.toFixed(2)}</p><button className="quick" onClick={e=>{e.stopPropagation();add(p)}}>QUICK ADD</button></article>)}</div></section>}

function Product({p,close,add,wish,setWish}){const [size,setSize]=useState(p.sizes[1]||p.sizes[0]),[color,setColor]=useState(p.colors[0]);return <div className="modal"><div className="product-modal"><button className="x" onClick={close}>×</button><img src={p.image}/><div><small>SS PASSION / {p.category}</small><h1>{p.name}</h1><h3>${p.price.toFixed(2)}</h3><p>Designed for effortless everyday styling. A refined SS PASSION essential with a modern relaxed fit.</p><b>COLOR — {color}</b><div className="chips">{p.colors.map(c=><button className={color===c?"selected":""} onClick={()=>setColor(c)}>{c}</button>)}</div><b>SIZE</b><div className="chips">{p.sizes.map(s=><button className={size===s?"selected":""} onClick={()=>setSize(s)}>{s}</button>)}</div><button className="primary" onClick={()=>{add(p,size,color);close()}}>ADD TO BAG</button><button className="secondary" onClick={()=>setWish(w=>w.includes(p.id)?w.filter(x=>x!==p.id):[...w,p.id])}>{wish.includes(p.id)?"♥ SAVED":"♡ WISHLIST"}</button><p className="fine">Worldwide shipping • Easy returns • Secure checkout</p></div></div></div>}

function Cart({cart,total,updateQty,remove,checkout}){return <section className="section"><small>SS PASSION / SHOPPING BAG</small><h1>YOUR BAG</h1>{!cart.length?<div className="empty">Your bag is empty.</div>:<div className="cart">{cart.map(i=><div className="cartrow"><img src={i.image}/><div><h3>{i.name}</h3><p>Size {i.size} • {i.color}</p><p>${i.price.toFixed(2)}</p><button onClick={()=>remove(i.id)}>Remove</button></div><div><button onClick={()=>updateQty(i.id,-1)}>−</button> {i.qty} <button onClick={()=>updateQty(i.id,1)}>+</button></div></div>)}<div className="summary"><b>SUBTOTAL</b><b>${total.toFixed(2)}</b><p>{total<150?`You're $${(150-total).toFixed(2)} away from FREE INTERNATIONAL SHIPPING.`:"You qualify for FREE INTERNATIONAL SHIPPING."}</p><button className="primary" onClick={checkout}>CHECKOUT</button><button className="paypal" onClick={checkout}>PAY WITH PAYPAL</button></div></div>}</section>}

function Checkout({total,cart}){const [done,setDone]=useState(false);return <section className="section checkout"><small>SS PASSION / CHECKOUT</small><h1>CHECKOUT</h1>{done?<div className="success"><h2>Thank you.</h2><p>Your demo order has been created. Connect PayPal credentials and a backend before accepting live payments.</p></div>:<div className="checkoutgrid"><form onSubmit={e=>{e.preventDefault();setDone(true)}}><label>Email<input type="email" required placeholder="you@example.com"/></label><label>Full name<input required/></label><label>Address<input required/></label><div className="tw"><label>City<input required/></label><label>Postal code<input required/></label></div><label>Country<select><option>India</option><option>United States</option><option>United Kingdom</option><option>United Arab Emirates</option><option>Germany</option></select></label><button className="primary">CONTINUE TO PAYPAL</button></form><aside className="order"><h3>ORDER SUMMARY</h3>{cart.map(i=><p>{i.name} × {i.qty}<span>${(i.price*i.qty).toFixed(2)}</span></p>)}<hr/><h3>Total <span>${total.toFixed(2)}</span></h3></aside></div>}</section>}

function Editorial({type}){return <section className="section editorial"><small>SS PASSION / {type.toUpperCase()}</small><h1>{type==="journal"?"JOURNAL":"COLLECTIONS"}</h1><div className="editorialhero"><h2>{type==="journal"?"Stories. Style. Inspiration.":"Timeless pieces. Modern attitude."}</h2><p>Curated for the SS PASSION customer.</p></div></section>}

function Admin({products,save,remove,close}){const blank={name:"",category:"Men",price:49,colors:["Black"],sizes:["S","M","L"],stock:10,badge:"NEW",image:"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85"};const [p,setP]=useState(blank),[editing,setEditing]=useState(false);const submit=e=>{e.preventDefault();save({...p,price:Number(p.price),stock:Number(p.stock),colors:p.colorsText?p.colorsText.split(",").map(x=>x.trim()):p.colors,sizes:p.sizesText?p.sizesText.split(",").map(x=>x.trim()):p.sizes});setP(blank);setEditing(false)};return <section className="admin section"><div className="shoptop"><div><small>SS PASSION / ADMIN</small><h1>STORE MANAGER</h1></div><button onClick={close}>EXIT ADMIN</button></div><form className="adminform" onSubmit={submit}><h2>{editing?"EDIT PRODUCT":"ADD PRODUCT"}</h2><input placeholder="Product name" value={p.name} onChange={e=>setP({...p,name:e.target.value})} required/><input type="number" placeholder="Price" value={p.price} onChange={e=>setP({...p,price:e.target.value})}/><select value={p.category} onChange={e=>setP({...p,category:e.target.value})}><option>Men</option><option>Women</option></select><input placeholder="Image URL" value={p.image} onChange={e=>setP({...p,image:e.target.value})}/><input placeholder="Sizes: S,M,L,XL" value={p.sizesText||p.sizes.join(",")} onChange={e=>setP({...p,sizesText:e.target.value})}/><input placeholder="Colors: Black,Cream" value={p.colorsText||p.colors.join(",")} onChange={e=>setP({...p,colorsText:e.target.value})}/><input type="number" placeholder="Stock" value={p.stock} onChange={e=>setP({...p,stock:e.target.value})}/><input placeholder="Badge: NEW / BESTSELLER / LIMITED" value={p.badge} onChange={e=>setP({...p,badge:e.target.value})}/><button className="primary">{editing?"SAVE CHANGES":"ADD PRODUCT"}</button></form><div className="adminlist">{products.map(x=><div><img src={x.image}/><span><b>{x.name}</b><small>{x.category} • ${x.price} • Stock {x.stock}</small></span><button onClick={()=>{setP({...x,colorsText:x.colors.join(","),sizesText:x.sizes.join(",")});setEditing(true)}}>EDIT</button><button onClick={()=>remove(x.id)}>DELETE</button></div>)}</div></section>}

createRoot(document.getElementById("root")).render(<App/>);